// Reading and writing puzzle batch files (src/puzzles/batch-NNN-slug.js).
//
// Batches are immutable once shipped: generators always WRITE a new file
// with the next number, they never edit an old one. The only sanctioned
// in-place edits are the line baker's (scripts/generate-lines.mjs), which
// adds playouts and self-heals verdicts without changing what a batch is.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';

export const PUZZLES_DIR = 'src/puzzles';

/** Parse one batch module (Node can't import Vite-globbed files directly). */
export function parseBatchFile(path) {
  return JSON.parse(
    readFileSync(path, 'utf8')
      .replace(/^\/\/.*\n/, '')
      .replace(/^export default /, '')
      .replace(/;\s*$/, ''),
  );
}

/** All batch files, oldest first: [{file, path, puzzles}]. */
export function readBatches(dir = PUZZLES_DIR) {
  return readdirSync(dir)
    .filter((f) => /^batch-\d+.*\.js$/.test(f))
    .sort()
    .map((file) => ({ file, path: `${dir}/${file}`, puzzles: parseBatchFile(`${dir}/${file}`) }));
}

/**
 * Write a NEW immutable batch: assigns the next batch number, stamps every
 * puzzle with a sequential id and meta.batch, and returns the file path.
 */
export function writeBatch({ label, generator, puzzles, dir = PUZZLES_DIR }) {
  const existing = readdirSync(dir).filter((f) => /^batch-\d+.*\.js$/.test(f)).sort();
  const nextNum = existing.length
    ? Number(existing[existing.length - 1].match(/^batch-(\d+)/)[1]) + 1
    : 1;
  const num = String(nextNum).padStart(3, '0');
  const batchMeta = { id: `b${num}`, label, createdAt: new Date().toISOString(), generator };
  const stamped = puzzles.map((puzzle, i) => ({
    ...puzzle,
    id: `${batchMeta.id}-${i + 1}`,
    meta: { ...puzzle.meta, batch: batchMeta },
  }));
  const slug = label.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40);
  const path = `${dir}/batch-${num}-${slug}.js`;
  writeFileSync(path, `// ${label} — generated by ${generator.split(' ')[0]}.\nexport default ${JSON.stringify(stamped)};\n`);
  return { path, batchId: batchMeta.id, count: stamped.length };
}
