// Generated by scripts/generate-puzzles.mjs — do not edit by hand.
export default [
  {
    "id": "gm-1",
    "name": "Anderssen–Kieseritzky, 1851",
    "description": "From Anderssen, Adolf vs Kieseritzky, Lionel, London 'Immortal Game' 1851, around move 17. Place the queen on one of the highlighted squares — one of them wins, the rest lose.",
    "fen": "rnb1k1nr/p2p1ppp/8/1pbN1N1P/4PBP1/3P1Q2/PPP5/R4KR1 b - - 0 1",
    "player": "b",
    "place": [
      "q"
    ],
    "candidates": [
      "a5",
      "e3",
      "e6"
    ],
    "solution": "e3",
    "source": {
      "white": "Anderssen, Adolf",
      "black": "Kieseritzky, Lionel",
      "event": "London 'Immortal Game'",
      "year": "1851",
      "moveNumber": 17,
      "removedFrom": "f6",
      "evals": {
        "win": 844,
        "losses": [
          -407,
          -349
        ]
      }
    }
  },
  {
    "id": "gm-2",
    "name": "Anderssen–Dufresne, 1852",
    "description": "From Anderssen, Adolf vs Dufresne, Jean, Berlin 'Evergreen Game' 1852, around move 20. Place the queen on one of the highlighted squares — one of them wins, the rest lose.",
    "fen": "1r2k1r1/pbppRp1p/1bn2P2/8/Q7/B1PB4/P4PPP/3R2K1 b - - 0 1",
    "player": "b",
    "place": [
      "q"
    ],
    "candidates": [
      "a6",
      "f3",
      "h3"
    ],
    "solution": "h3",
    "source": {
      "white": "Anderssen, Adolf",
      "black": "Dufresne, Jean",
      "event": "Berlin 'Evergreen Game'",
      "year": "1852",
      "moveNumber": 20,
      "removedFrom": "f3",
      "evals": {
        "win": 1070,
        "losses": [
          -9992,
          -323
        ]
      }
    }
  },
  {
    "id": "gm-3",
    "name": "Byrne–Fischer, 1956",
    "description": "From Byrne, Donald vs Fischer, Robert James, Third Rosenwald Trophy 'Game of the Century' 1956, around move 10. Place the rook on one of the highlighted squares — one of them wins, the rest lose.",
    "fen": "r1bq1rk1/pp2ppbp/1np2np1/8/2QPPB2/2N2N2/PP3PPP/4KB1R w - - 0 1",
    "player": "w",
    "place": [
      "r"
    ],
    "candidates": [
      "d5",
      "f5",
      "g4"
    ],
    "solution": "d5",
    "source": {
      "white": "Byrne, Donald",
      "black": "Fischer, Robert James",
      "event": "Third Rosenwald Trophy 'Game of the Century'",
      "year": "1956",
      "moveNumber": 10,
      "removedFrom": "d1",
      "evals": {
        "win": 414,
        "losses": [
          -380,
          -405
        ]
      }
    }
  },
  {
    "id": "gm-4",
    "name": "Byrne–Fischer, 1956",
    "description": "From Byrne, Donald vs Fischer, Robert James, Third Rosenwald Trophy 'Game of the Century' 1956, around move 16. Place the rook on one of the highlighted squares — one of them wins, the rest lose.",
    "fen": "r4rk1/pp2Bpbp/1qp3p1/8/2BP2b1/Q1n2N2/P4PPP/4K2R w - - 0 1",
    "player": "w",
    "place": [
      "r"
    ],
    "candidates": [
      "a6",
      "e8",
      "f1"
    ],
    "solution": "a6",
    "source": {
      "white": "Byrne, Donald",
      "black": "Fischer, Robert James",
      "event": "Third Rosenwald Trophy 'Game of the Century'",
      "year": "1956",
      "moveNumber": 16,
      "removedFrom": "d1",
      "evals": {
        "win": 416,
        "losses": [
          -354,
          -329
        ]
      }
    }
  },
  {
    "id": "gm-5",
    "name": "Rotlewi–Rubinstein, 1907",
    "description": "From Rotlewi, Georg vs Rubinstein, Akiba, Lodz 'Rubinstein's Immortal' 1907, around move 19. Place the queen on one of the highlighted squares — one of them wins, the rest lose.",
    "fen": "2rr2k1/1bb1qppp/p3pn2/1p6/1P2PP2/P1NB4/1B4PP/R4RK1 w - - 0 1",
    "player": "w",
    "place": [
      "q"
    ],
    "candidates": [
      "b3",
      "d4",
      "d7"
    ],
    "solution": "d7",
    "source": {
      "white": "Rotlewi, Georg",
      "black": "Rubinstein, Akiba",
      "event": "Lodz 'Rubinstein's Immortal'",
      "year": "1907",
      "moveNumber": 19,
      "removedFrom": "e2",
      "evals": {
        "win": 362,
        "losses": [
          -303,
          -396
        ]
      }
    }
  },
  {
    "id": "gm-6",
    "name": "Rotlewi–Rubinstein, 1907",
    "description": "From Rotlewi, Georg vs Rubinstein, Akiba, Lodz 'Rubinstein's Immortal' 1907, around move 22. Place the rook on one of the highlighted squares — one of them wins, the rest lose.",
    "fen": "2rr2k1/1b3ppp/pb2p3/1p2P3/1P2BPnq/P1N5/1B2Q1PP/5R1K w - - 0 1",
    "player": "w",
    "place": [
      "r"
    ],
    "candidates": [
      "c2",
      "g1",
      "h5"
    ],
    "solution": "h5",
    "source": {
      "white": "Rotlewi, Georg",
      "black": "Rubinstein, Akiba",
      "event": "Lodz 'Rubinstein's Immortal'",
      "year": "1907",
      "moveNumber": 22,
      "removedFrom": "a1",
      "evals": {
        "win": 536,
        "losses": [
          -349,
          -350
        ]
      }
    }
  },
  {
    "id": "gm-7",
    "name": "Kasparov–Topalov, 1999",
    "description": "From Kasparov, Garry vs Topalov, Veselin, Hoogovens 'Kasparov's Immortal' 1999, around move 11. Place the rook on one of the highlighted squares — one of them wins, the rest lose.",
    "fen": "3qk2r/pb1n1p1p/2pp1npQ/1p2p3/3PP3/P1N2P2/1PP1N1PP/2KR1B1R b - - 0 1",
    "player": "b",
    "place": [
      "r"
    ],
    "candidates": [
      "b3",
      "g4",
      "h5"
    ],
    "solution": "h5",
    "source": {
      "white": "Kasparov, Garry",
      "black": "Topalov, Veselin",
      "event": "Hoogovens 'Kasparov's Immortal'",
      "year": "1999",
      "moveNumber": 11,
      "removedFrom": "a8",
      "evals": {
        "win": 522,
        "losses": [
          -311,
          -352
        ]
      }
    }
  },
  {
    "id": "gm-8",
    "name": "Kasparov–Topalov, 1999",
    "description": "From Kasparov, Garry vs Topalov, Veselin, Hoogovens 'Kasparov's Immortal' 1999, around move 14. Place the rook on one of the highlighted squares — one of them wins, the rest lose.",
    "fen": "2k4r/1b1nqp1p/p1pp1npQ/1p2p3/3PP3/PNN2P2/1PP3PP/1K1R1B1R b - - 0 1",
    "player": "b",
    "place": [
      "r"
    ],
    "candidates": [
      "a2",
      "e2",
      "h3"
    ],
    "solution": "h3",
    "source": {
      "white": "Kasparov, Garry",
      "black": "Topalov, Veselin",
      "event": "Hoogovens 'Kasparov's Immortal'",
      "year": "1999",
      "moveNumber": 14,
      "removedFrom": "d8",
      "evals": {
        "win": 509,
        "losses": [
          -315,
          -315
        ]
      }
    }
  }
];
